### ISSUE TITLE
Remove suggestion validation logic from SuggestionEngine

### ISSUE THREAD

**Issue by patmay** [yo09975/Clue-less#116]
SuggestionEngine does not need to validate that a suggestion contains one room/char/weapon. This is currently done in make_suggestion. it should be removed.

make suggestion should return true or false for only the two conditions below
true - someone can disprove the suggestion
false - someone cannot disprove the suggestion

@brentongk

**Comment by yo09975** [comment]
I agree with this except that I believe you should not be able to create a Suggestion with the wrong card types. I propose to add this logic into the Suggestion constructor.

**Comment by brentongk** [comment]
I can move the validation to the suggestion constructor. What should we do if it is an invalid input? Send a notify message? Raise an error?
