### ISSUE TITLE
Update failing tests using PlayerList to use the PlayerList.clear() function

### ISSUE THREAD

**Issue by patmay** [yo09975/Clue-less#118]

**Comment by yo09975** [comment]
The real problem is the singleton, perhaps experiment with removing the instance?

Otherwise yeah, a clear function call will allow the tests to pass..

**Comment by yo09975** [comment]
I've been looking at all the unit tests that are failing. I noticed there's an assertion failure for gamestate where get_current_player is returning 12. There should only be a maximum of 6 elements in the playerlist. This has to be a bug

**Comment by yo09975** [comment]
Found bug in is_valid_move() where player_list.get_player() returns None but then player.get_current_location() is invoked. Added return False to check for successful player return

**Comment by yo09975** [comment]
There are some more sneaky bugs about that are preventing all of the tests from passing.
