### ISSUE TITLE
Card cleanup

### ISSUE THREAD

**Issue by yo09975** [yo09975/Clue-less#137]
Clean up Card to only _require_ a card_id and card type. Right now, we initialize cards with both strings as the same value e.g. Card("Colonel Mustard", CardType.SUSPECT, "Colonel Mustard").

The "nice to have" for changing names of cards and the such should perhaps be implemented by an optional argument in the constructor.

Rename the extra attribute to "alias" or similar, add as an optional argument to constructor, and refactor.

This is a nice to have, low priority.

**Comment by michael-s-myer** [comment]
i agree this work is appropriate for the backlog.
