### ISSUE TITLE
De-squash two messages sent rapidly from server to client

### ISSUE THREAD

**Issue by patmay** [yo09975/Clue-less#156]
Client is receiving one message from cli.read_message() that looks like the following:

> {"uuid": "b01dea5f-e301-4e11-864f-a56b0e6032d3", "msg_type": 18, "payload": "{\"Colonel Mustard\": \"{\\\"name\\\": \\\"Colonel Mustard\\\", \\\"card_type\\\": 1, \\\"card_id\\\": \\\"Colonel Mustard\\\"}\", \"Billiard Room\": \"{\\\"name\\\": \\\"Billiard Room\\\", \\\"card_type\\\": 2, \\\"card_id\\\": \\\"Billiard Room\\\"}\", \"Mr. Green\": \"{\\\"name\\\": \\\"Mr. Green\\\", \\\"card_type\\\": 1, \\\"card_id\\\": \\\"Mr. Green\\\"}\", \"Dining Room\": \"{\\\"name\\\": \\\"Dining Room\\\", \\\"card_type\\\": 2, \\\"card_id\\\": \\\"Dining Room\\\"}\", \"Library\": \"{\\\"name\\\": \\\"Library\\\", \\\"card_type\\\": 2, \\\"card_id\\\": \\\"Library\\\"}\", \"Knife\": \"{\\\"name\\\": \\\"Knife\\\", \\\"card_type\\\": 3, \\\"card_id\\\": \\\"Knife\\\"}\", \"Miss Scarlet\": \"{\\\"name\\\": \\\"Miss Scarlet\\\", \\\"card_type\\\": 1, \\\"card_id\\\": \\\"Miss Scarlet\\\"}\", \"Lead Pipe\": \"{\\\"name\\\": \\\"Lead Pipe\\\", \\\"card_type\\\": 3, \\\"card_id\\\": \\\"Lead Pipe\\\"}\", \"Study\": \"{\\\"name\\\": \\\"Study\\\", \\\"card_type\\\": 2, \\\"card_id\\\": \\\"Study\\\"}\"}"}**{"uuid": "b01dea5f-e301-4e11-864f-a56b0e6032d3", "msg_type": 16, "payload": "Currently taking their turn:"}{"uuid": "b01dea5f-e301-4e11-864f-a56b0e6032d3", "msg_type": 19, "payload": "{\"was_transferred\": false}"}**

This appears to be a common problem with sockets in general. See:
https://stackoverflow.com/questions/17664544/one-recv-gets-two-or-more-send-in-python-sockets
https://stackoverflow.com/questions/28583242/client-receiving-two-separate-message-as-one-with-python-socket

Completion should include a test for this scenario

**Comment by yo09975** [comment]
I'll look into this
