### ISSUE TITLE
Move Jenkins from 8080 so that the tests stop failing

### ISSUE THREAD

**Issue by yo09975** [yo09975/Clue-less#215]
Our server runs on 8080 so that the JHU firewall doesn't block us. Jenkins also runs on 8080, which means the tests for networking fail since they spin up a ('0.0.0.0', 8080) but Jenkins is already bound to that port.

**Comment by yo09975** [comment]
https://stackoverflow.com/questions/23769478/how-to-change-port-for-jenkins-window-service-when-8080-is-being-used

**Comment by stephensmeal** [comment]
Great job Pat.
